# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.


# Site Settings
locale                   : "en-US"
title                    : Gavin Sneyd
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : Gavin Sneyd
description              : Gavin Sneyd - Projects and CV 
baseurl                  : "/portfolio-ges253-ctrl" # Set this to your repo name

# Theme and Style
theme: jekyll-theme-minimal
color_scheme: dark # light/default, dark, or aqua

sass:
  style: compressed

# Outputting
permalink: /:categories/:title/

collections:
  pages:
    output: true
  projects:
    output: true
    permalink: /projects/:path/

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

